import { InventoryItem } from './types';

export const mockInventory: InventoryItem[] = [
  {
    id: '1',
    date: '2023-10-25',
    mainReason: 'Restock',
    dataType: 'Inbound',
    fromLocation: 'Supplier A',
    toLocation: 'Warehouse 1',
    boxBarcode: 'BX-1001',
    itemBarcode: 'ITM-9901',
    countedQuantity: 50,
    totalQuantity: 500,
    storePrice: 15.99,
    changedPrice: 15.99,
    imageUrl: 'https://picsum.photos/seed/item1/200/200',
    expiryImageUrl: 'https://picsum.photos/seed/exp1/200/200',
    perBoxImageUrl: 'https://picsum.photos/seed/box1/200/200',
    imageLinkUrl: 'https://picsum.photos/seed/item1/800/800',
    totalScanTime: '10:30 AM',
    countNumber: 1,
    ofHowManyItems: 10,
    totalPiecesCounted: 50,
    details: 'Hydrating Face Serum 30ml',
  },
  {
    id: '2',
    date: '2023-10-25',
    mainReason: 'Restock',
    dataType: 'Inbound',
    fromLocation: 'Supplier B',
    toLocation: 'Warehouse 1',
    boxBarcode: 'BX-1002',
    itemBarcode: 'ITM-9902',
    countedQuantity: 100,
    totalQuantity: 1000,
    storePrice: 8.50,
    changedPrice: 8.50,
    imageUrl: 'https://picsum.photos/seed/item2/200/200',
    expiryImageUrl: 'https://picsum.photos/seed/exp2/200/200',
    perBoxImageUrl: 'https://picsum.photos/seed/box2/200/200',
    imageLinkUrl: 'https://picsum.photos/seed/item2/800/800',
    totalScanTime: '11:15 AM',
    countNumber: 2,
    ofHowManyItems: 20,
    totalPiecesCounted: 100,
    details: 'Soothing Aloe Vera Gel 250ml',
  },
  {
    id: '3',
    date: '2023-10-26',
    mainReason: 'Transfer',
    dataType: 'Outbound',
    fromLocation: 'Warehouse 1',
    toLocation: 'Store Front',
    boxBarcode: 'BX-1003',
    itemBarcode: 'ITM-9903',
    countedQuantity: 20,
    totalQuantity: 150,
    storePrice: 22.00,
    changedPrice: 20.00,
    imageUrl: 'https://picsum.photos/seed/item3/200/200',
    expiryImageUrl: 'https://picsum.photos/seed/exp3/200/200',
    perBoxImageUrl: 'https://picsum.photos/seed/box3/200/200',
    imageLinkUrl: 'https://picsum.photos/seed/item3/800/800',
    totalScanTime: '09:00 AM',
    countNumber: 1,
    ofHowManyItems: 5,
    totalPiecesCounted: 20,
    details: 'Vitamin C Brightening Toner',
  },
  {
    id: '4',
    date: '2023-10-26',
    mainReason: 'Return',
    dataType: 'Inbound',
    fromLocation: 'Customer',
    toLocation: 'Warehouse 2',
    boxBarcode: 'BX-1004',
    itemBarcode: 'ITM-9904',
    countedQuantity: 1,
    totalQuantity: 10,
    storePrice: 45.00,
    changedPrice: 45.00,
    imageUrl: 'https://picsum.photos/seed/item4/200/200',
    expiryImageUrl: 'https://picsum.photos/seed/exp4/200/200',
    perBoxImageUrl: 'https://picsum.photos/seed/box4/200/200',
    imageLinkUrl: 'https://picsum.photos/seed/item4/800/800',
    totalScanTime: '02:45 PM',
    countNumber: 1,
    ofHowManyItems: 1,
    totalPiecesCounted: 1,
    details: 'Premium Anti-Aging Night Cream',
  },
  {
    id: '5',
    date: '2023-10-27',
    mainReason: 'Audit',
    dataType: 'Internal',
    fromLocation: 'Warehouse 1',
    toLocation: 'Warehouse 1',
    boxBarcode: 'BX-1005',
    itemBarcode: 'ITM-9905',
    countedQuantity: 200,
    totalQuantity: 200,
    storePrice: 5.00,
    changedPrice: 5.00,
    imageUrl: 'https://picsum.photos/seed/item5/200/200',
    expiryImageUrl: 'https://picsum.photos/seed/exp5/200/200',
    perBoxImageUrl: 'https://picsum.photos/seed/box5/200/200',
    imageLinkUrl: 'https://picsum.photos/seed/item5/800/800',
    totalScanTime: '04:20 PM',
    countNumber: 5,
    ofHowManyItems: 50,
    totalPiecesCounted: 200,
    details: 'Daily UV Defense Sunscreen SPF50',
  }
];
